# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Harsh Lara
tagline:          'Learning new things'
description:      'Personal Webpage'
url:              https://codinglara.github.io
baseurl:          /

author:
  name:           'Harsh Lara'
  url:            https://github.com/codinglara

paginate:         5

plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/codinglara/codinglara.github.io
